apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: event-management-app
type: Opaque
stringData:
  DB_URL: "${DB_URL}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  MAIL_USERNAME: "${MAIL_USERNAME}"
  MAIL_APP_PASSWORD: "${MAIL_APP_PASSWORD}"
  CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
  CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
  CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
