apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: event-management-app
type: Opaque
data:
  DB_URL: "jdbc:mysql://db:3306/event_management?useSSL=false&allowPublicKeyRetrieval=true"
  DB_USERNAME: "ZXZlbnRfbWFuYWdlbWVudA=="
  DB_PASSWORD: "RXw5bkx2bn5VTnRHQ09rSg=="
  JWT_SECRET: "VEhBWV9KUkVNT05BVEVfU0VDUkVUVElOR19TRUNSRVQ="
  MAIL_USERNAME: "dHVhbnBoYW0uNTQxN0BnbWFpbC5jb20="
  MAIL_APP_PASSWORD: "ZmRieCBlcHpjIGx1dHYgbWtjeg=="
  CLOUDINARY_CLOUD_NAME: "ZG9idGdkdnpr"
  CLOUDINARY_API_KEY: "NDY0MTUzODcxNjcxMzk2"
  CLOUDINARY_API_SECRET: "S1JKbFJQQnVyZUxPT3EyTDJmWENlS2Z3SkVZ"
